CREATE GLOBAL TEMPORARY TABLE REP.REP_CORE_TMP 
 (  REP_ID NUMBER, 
ROW_NUMBER NUMBER, 
DATA CLOB
 ) ON COMMIT PRESERVE ROWS;
 
 --=========================================================
CREATE TABLE REP_CORE_FOLDER 
 (  ID RAW(20) DEFAULT sys_guid() NOT NULL ENABLE, 
NAME VARCHAR2(200), 
 CONSTRAINT PK_REP_CORE_FOLDER PRIMARY KEY (ID)
 ) ;
 --=========================================================
   CREATE TABLE REP_CORE_USERS 
   (  ID NUMBER NOT NULL ENABLE, 
  USERNAME VARCHAR2(100) NOT NULL ENABLE, 
  PASSWORD VARCHAR2(100) NOT NULL ENABLE, 
  CREATED_AT DATE DEFAULT SYSDATE, 
  MODIFIED_AT DATE DEFAULT SYSDATE, 
  IP_ADDRESS VARCHAR2(20), 
  LAST_LOGIN DATE, 
  STATUS VARCHAR2(1), 
  EMAIL VARCHAR2(100), 
  ROLE VARCHAR2(100), 
  IS_ENABLED NUMBER, 
   CONSTRAINT PK_CORE_USERS PRIMARY KEY (ID));
--=========================================================
  CREATE TABLE REP_CORE_NAME 
   (  ID RAW(16) DEFAULT SYS_GUID() NOT NULL ENABLE, 
  NAME VARCHAR2(100), 
  PACKAGE_NAME VARCHAR2(100), 
  STATUS CHAR(1), 
  CREATED_AT DATE DEFAULT SYSDATE, 
  MODIFIED_AT DATE DEFAULT SYSDATE, 
  TEMPLATE VARCHAR2(100), 
  FOLDER_ID RAW(16), 
   PRIMARY KEY (ID), 
   CONSTRAINT FK_REP_FOLDER FOREIGN KEY (FOLDER_ID)
    REFERENCES REP_CORE_FOLDER (ID) ENABLE);     
 --=========================================================
   CREATE TABLE REP_CORE_SCHEDULE 
   (  ID RAW(16) DEFAULT SYS_GUID() NOT NULL ENABLE, 
  REP_ID RAW(16) NOT NULL ENABLE, 
  USER_ID NUMBER NOT NULL ENABLE, 
  PARAMS CLOB, 
  FILE_FORMAT VARCHAR2(10) DEFAULT 'xlsx', 
  CRON_EXPR VARCHAR2(100), 
  RUN_AT TIMESTAMP (6), 
  IS_ACTIVE NUMBER(1,0) DEFAULT 1, 
  LAST_RUN TIMESTAMP (6), 
  LAST_STATUS VARCHAR2(20), 
  LAST_ERROR VARCHAR2(1000), 
  LAST_FILE VARCHAR2(500), 
  CREATED_AT TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
  IS_DELETED NUMBER DEFAULT 0, 
   PRIMARY KEY (ID), 
   CONSTRAINT FK_SCHED_REP FOREIGN KEY (REP_ID)
    REFERENCES REP_CORE_NAME (ID) ENABLE, 
   CONSTRAINT FK_SCHED_USER FOREIGN KEY (USER_ID)
    REFERENCES REP_CORE_USERS (ID) ENABLE
   );
   --=========================================================
   
  CREATE TABLE REP_CORE_PARAMS 
   (	REP_ID RAW(16), 
	PARAM_NAME VARCHAR2(100), 
	PARAM_TYPE VARCHAR2(100), 
	PARAM_ORDER NUMBER, 
	PARAM_VIEW NVARCHAR2(200), 
	DEF_VALUE VARCHAR2(4000), 
	 CONSTRAINT FK_REP_PARAMS FOREIGN KEY (REP_ID)
	  REFERENCES REP_CORE_NAME (ID) ENABLE
   );
 --=========================================================
   
  CREATE TABLE REP_CORE_EXCEL_TMP 
   (	ID RAW(20), 
	REP_ID RAW(20), 
	ROW_NUMBER NUMBER, 
	IMPORT_DATA CLOB, 
	REP_LOG_ID NUMBER, 
	 CONSTRAINT FK_CORE_EXCEL_TMP FOREIGN KEY (REP_ID)
	  REFERENCES REP_CORE_NAME (ID) ENABLE
   );
 --=========================================================
 
  CREATE TABLE REP_CORE_ACCESS 
   (	REP_ID RAW(16), 
	USER_ID NUMBER, 
	SALARY_ACCESS NUMBER(1,0), 
	CREATED_AT DATE DEFAULT SYSDATE, 
	 CONSTRAINT FK_REP_ROLE FOREIGN KEY (REP_ID)
	  REFERENCES REP_CORE_NAME (ID) ENABLE
   ) ;
 --=========================================================    
   CREATE TABLE REP_CORE_LOG 
   (  ID NUMBER, 
  REP_ID RAW(16), 
  USER_ID NUMBER, 
  BG_TIME DATE, 
  END_TIME DATE, 
  STATUS VARCHAR2(3), 
  PERCENTAGE VARCHAR2(3), 
  ERROR_MSG VARCHAR2(200), 
  APL_DT DATE DEFAULT sysdate, 
  PARAMS VARCHAR2(4000), 
   CONSTRAINT FK_LOG_REP FOREIGN KEY (REP_ID)
    REFERENCES REP_CORE_NAME (ID) ENABLE
   ) ;