-- Create sequence 
CREATE SEQUENCE SEQ_FOR_VAL
MINVALUE 1
MAXVALUE 9999999999999999999999999999
START WITH 1481
INCREMENT BY 1
CACHE 20;

CREATE TABLE REP_CORE_ACCESS
   (  REP_ID RAW(16),
  USER_ID NUMBER,
  SALARY_ACCESS NUMBER(1,0),
  CREATED_AT DATE DEFAULT SYSDATE,
   CONSTRAINT FK_REP_ROLE FOREIGN KEY (REP_ID)
    REFERENCES DM1.REP_CORE_NAME (ID) ENABLE
   ) ;


CREATE TABLE REP_CORE_LOG
   (  ID NUMBER,
  REP_ID RAW(16),
  USER_ID NUMBER,
  BG_TIME DATE,
  END_TIME DATE,
  STATUS VARCHAR2(3),
  PERCENTAGE VARCHAR2(3),
  ERROR_MSG VARCHAR2(200),
  APL_DT DATE DEFAULT sysdate,
   CONSTRAINT FK_LOG_REP FOREIGN KEY (REP_ID)
    REFERENCES DM1.REP_CORE_NAME (ID) ENABLE
   ) ;


CREATE TABLE REP_CORE_NAME
   (  ID RAW(16) DEFAULT SYS_GUID(),
  NAME VARCHAR2(100),
  PACKAGE_NAME VARCHAR2(100),
  STATUS CHAR(1),
  CREATED_AT DATE DEFAULT SYSDATE,
  MODIFIED_AT DATE DEFAULT SYSDATE,
  TEMPLATE VARCHAR2(100),
   PRIMARY KEY (ID)) ;


CREATE TABLE REP_CORE_PARAMS
   (  REP_ID RAW(16),
  PARAM_NAME VARCHAR2(100),
  PARAM_TYPE VARCHAR2(100),
  PARAM_ORDER NUMBER,
  PARAM_VIEW NVARCHAR2(200),
  DEF_VALUE VARCHAR2(4000),
   CONSTRAINT FK_REP_PARAMS FOREIGN KEY (REP_ID)
    REFERENCES DM1.REP_CORE_NAME (ID) ENABLE
   );


-- Create table
create table REP_CORE_SCHEDULE
(
  id          RAW(16) default SYS_GUID() not null,
  rep_id      RAW(16) not null,
  user_id     NUMBER not null,
  params      CLOB,
  file_format VARCHAR2(10) default 'xlsx',
  cron_expr   VARCHAR2(100),
  run_at      TIMESTAMP(6),
  is_active   NUMBER(1) default 1,
  last_run    TIMESTAMP(6),
  last_status VARCHAR2(20),
  last_error  VARCHAR2(1000),
  last_file   VARCHAR2(500),
  created_at  TIMESTAMP(6) default SYSTIMESTAMP,
  is_deleted  NUMBER default 0
);
-- Create/Recreate primary, unique and foreign key constraints 
alter table REP_CORE_SCHEDULE
  add primary key (ID);
alter table REP_CORE_SCHEDULE
  add constraint FK_SCHED_REP foreign key (REP_ID)
  references REP_CORE_NAME (ID);
alter table REP_CORE_SCHEDULE
  add constraint FK_SCHED_USER foreign key (USER_ID)
  references REP_CORE_USERS (ID);

CREATE TABLE DM1.REP_CORE_USERS
   (  ID NUMBER,
  USERNAME VARCHAR2(100) NOT NULL ENABLE,
  PASSWORD VARCHAR2(100) NOT NULL ENABLE,
  CREATED_AT DATE DEFAULT SYSDATE,
  MODIFIED_AT DATE DEFAULT SYSDATE,
  IP_ADDRESS VARCHAR2(20),
  LAST_LOGIN DATE,
  STATUS VARCHAR2(1),
  EMAIL VARCHAR2(100),
  ROLE VARCHAR2(100),
  IS_ENABLED NUMBER,
   CONSTRAINT PK_CORE_USERS PRIMARY KEY (ID) 
   ) ;


CREATE TABLE REP_CORE_EXCEL_TMP
   (  ID RAW(20),
  REP_ID RAW(20),
  ROW_NUMBER NUMBER,
  IMPORT_DATA CLOB,
  REP_LOG_ID NUMBER,
   CONSTRAINT FK_CORE_EXCEL_TMP FOREIGN KEY (REP_ID)
    REFERENCES DM1.REP_CORE_NAME (ID) ENABLE
   ) ;


CREATE GLOBAL TEMPORARY TABLE REP_CORE_TMP
   (  REP_ID NUMBER,
  ROW_NUMBER NUMBER,
  DATA CLOB
   ) ON COMMIT PRESERVE ROWS ;
