spring.application.name=report-system

server.port=8080
server.address=0.0.0.0
server.servlet.context-path=/api

jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000

spring.datasource.url=

# HikariCP sozlamalari
spring.datasource.hikari.connection-test-query=SELECT 1 FROM DUAL
spring.datasource.hikari.keepalive-time=60000
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=1200000
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.validation-timeout=5000
spring.datasource.hikari.connection-timeout=30000

spring.datasource.username=test
spring.datasource.password=test
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

admin.username: admin
admin.password: admin123!
admin.email:  
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

# Swagger context-path ni bilishi uchun
springdoc.swagger-ui.config-url=/api/v3/api-docs/swagger-config
springdoc.swagger-ui.url=/api/v3/api-docs

report.download.dir=C:/Users/user/Downloads/
report.export.dir=C:/Users/user/Downloads/
report.scheduled-reports.dir=D:/Report Projct/report-system-backend/scheduled-reports

springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.try-it-out-enabled=true
springdoc.swagger-ui.operations-sorter=method

# Fayl hajmi
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# Har bir batch nechta qator
app.batch.size=5000
