spring.application.name=report-system

server.port=8080
server.address=0.0.0.0
server.servlet.context-path=/api

jwt.secret=yoursecretkey123456789
jwt.expiration=86400000

spring.datasource.url= 

spring.datasource.username=test
spring.datasource.password=test
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

admin.username: admin
admin.password: admin123!
admin.email: email@gamil.com 

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

# Swagger context-path ni bilishi uchun
springdoc.swagger-ui.config-url=/api/v3/api-docs/swagger-config
springdoc.swagger-ui.url=/api/v3/api-docs

report.download.dir=C:/Downloads/

springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.try-it-out-enabled=true
springdoc.swagger-ui.operations-sorter=method
